### PR TITLE
Add blog post on alien talks at mixit17

### PR DESCRIPTION
**Pull request by cexbrayat**

### CODE REVIEW

**Comment by cexbrayat** [comment]
Amended the PR with the english translation

**Comment by clacote** [comment]
I probably missed something, but I tried to run your branch, and your post is not listed, neither in French, nor in English:
image
image

**Comment by cexbrayat** [comment]
Maybe I messed up something, but I had to drop the mongo db collection `db.post.remove({})` and relaunch the app to workaround the same thing

**Comment by sdeleuze** [comment]
Yes, the data is not anymore automatically imported if data already exists to avoid accidental override if PROD data, so your workaround is the right thing to do. I will shortly introduce a backend for editing blog.

**Pull request merged**
